apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app-deployment
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
    spec:
      containers:
      - name: trading-app
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
